### ISSUE TITLE
FIXME: SteamworksApp is producing/returning IDs with BOM mark for mod 2642161586

### ISSUE THREAD

**Issue by NeveHanter** [RimSort/RimSort#119]
**Describe the bug**
I'm unable to build the Steam DB due to one of the mods having its PublishedFileId.txt encoded with UTF-8 with BOM (I have not modified this file after having this mod downloaded from Steam Workshop).

Its the https://steamcommunity.com/sharedfiles/filedetails/?id=2641289639 mod.

First exception is:
```
[2023-06-22 22:56:13] ERROR: Dummy-19 The main application loop has failed with an uncaught exception
Traceback (most recent call last):
  File "/home/nevehanter/Games/RimSort/util/metadata.py", line 119, in run
    dynamic_query.create_steam_db(database, publishedfileids)
  File "/home/nevehanter/Games/RimSort/util/steam/webapi/wrapper.py", line 158, in create_steam_db
    query = self.ISteamUGC_GetAppDependencies(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nevehanter/Games/RimSort/util/steam/webapi/wrapper.py", line 450, in ISteamUGC_GetAppDependencies
    queries = [
              ^
  File "/home/nevehanter/Games/RimSort/util/steam/webapi/wrapper.py", line 452, in <listcomp>
    pfid_or_pfids=[eval(str_pfid) for str_pfid in chunk], interval=1
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nevehanter/Games/RimSort/util/steam/webapi/wrapper.py", line 452, in <listcomp>
    pfid_or_pfids=[eval(str_pfid) for str_pfid in chunk], interval=1
                   ^^^^^^^^^^^^^^
  File "<string>", line 1
    ﻿2642161586
    ^
SyntaxError: invalid non-printable character U+FEFF
```
Second exception after truncating the BOM mark by adding crude `.replace("/ufeff", "")` in line 452:
```
[2023-06-22 22:58:34] ERROR: Dummy-19 The main application loop has failed with an uncaught exception
Traceback (most recent call last):
  File "/home/nevehanter/Games/RimSort/util/metadata.py", line 119, in run
    dynamic_query.create_steam_db(database, publishedfileids)
  File "/home/nevehanter/Games/RimSort/util/steam/webapi/wrapper.py", line 158, in create_steam_db
    query = self.ISteamUGC_GetAppDependencies(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nevehanter/Games/RimSort/util/steam/webapi/wrapper.py", line 468, in ISteamUGC_GetAppDependencies
    if int(pfid) in pfids_appid_deps:
       ^^^^^^^^^
ValueError: invalid literal for int() with base 10: '\ufeff2642161586'
```

**To Reproduce**
1. Download 2642161586 with Steam Workshop,
2. try building the Steam DB

**Expected behavior**
No exceptions and Steam DB successfully built.

**Screenshots**
-

**Please complete the following information:**
 - OS: ArchLinux
 - RimSort version: master (0c8cc16b)
 - Please provide a `RimSort.log`: Really nothing except the things above.
 - Are you running from Python interpreter or from a compiled RimSort release? Python interpreter, version 3.11.3

**Additional context**
-

**Comment by twstagg** [comment]
@NeveHanter Thank you very much for your report. I will add some additional sanitation and fix in next release.
