### ISSUE TITLE
FIXME: Crash to desktop renders ModConfig corrupt: need to start rimworld and add all my mods again. Rinse and repeat.

### ISSUE THREAD

**Issue by abmpicoli2** [RimSort/RimSort#152]
**Describe the bug**
Any corrupt xml seems to crash the program and then the ModConfig.xml is overwritten with a zero bytes file, causing further action in the Rimsort application to not start anymore.
**To Reproduce**
1. Remove ModConfig.xml from the configuration folder, so rimworld creates a new one.
2. Start rimsort to add extra mods to the list. There is no evidence of which of the mods are corrupt so I can't tell for sure which one is. 
3. Click the save mod list.
**Expected behavior**
Some error should be shown, all I see is some cryptical python error in the console. And definitely ModConfig.xml should not become a corrupt zero-bytes file.

BTW the upload log doesn't show the link to where the log was stored. So what I've attached here is a ctrl-a of the rimsort console.
[crash_log.txt](https://github.com/RimSort/RimSort/files/12413567/crash_log.txt)

**Screenshots**

**Please complete the following information:**
 - OS: [e.g. iOS] Windows 64
 - RimSort version: Edge fded5ab
 - Please provide a `RimSort.log`:
 - Are you running from Python interpreter or from a compiled RimSort release? I've downloaded the package and I'm running Rimsort.exe directly using a shortcut from the windows desktop.

**Additional context**

**Comment by abmpicoli2** [comment]
![image](https://github.com/RimSort/RimSort/assets/37077317/8cea6cec-93dc-4671-8440-4c158f84a5ec)
this is what trying to restart rimsort shows after. No message, nothing, a red box and a stacktrace

```
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
[2023-08-22 20:07:05] WARNING: Non-Linux platform detected: using multiprocessing.freeze_support() & setting 'spawn' as MP method
[2023-08-22 20:07:14] ERROR: The main application instantiation has failed with an uncaught exception:
[2023-08-22 20:07:14] ERROR: Traceback (most recent call last):
  File "E:\programs\Rimsort-Edge-fded5ab-WindowsX86_64\RimSort\RimSort.py", line 254, in main_thread
  File "E:\programs\Rimsort-Edge-fded5ab-WindowsX86_64\RimSort\RimSort.py", line 181, in __initialize_content
  File "E:\programs\Rimsort-Edge-fded5ab-WindowsX86_64\RimSort\view\main_content_panel.py", line 1289, in _do_refresh
  File "E:\programs\Rimsort-Edge-fded5ab-WindowsX86_64\RimSort\view\main_content_panel.py", line 765, in __repopulate_lists
  File "E:\programs\Rimsort-Edge-fded5ab-WindowsX86_64\RimSort\util\mods.py", line 228, in get_active_inactive_mods
  File "E:\programs\Rimsort-Edge-fded5ab-WindowsX86_64\RimSort\util\xml.py", line 30, in xml_path_to_json
  File "E:\programs\Rimsort-Edge-fded5ab-WindowsX86_64\RimSort\xmltodict.py", line 378, in parse
xml.parsers.expat.ExpatError: no element found: line 2, column 0
```

**Comment by twstagg** [comment]
Can you please provide your `RimSort.log`?

**Comment by twstagg** [comment]
Pleaase also try the latest release: https://github.com/RimSort/RimSort/releases/tag/Edge

**Comment by abmpicoli** [comment]
The problem is "I don't have the issue anymore". In the end, I've simply thrown the whole modlist away and started from scratch. I will try to make a "bad mod" to reproduce the issue.

**Comment by abmpicoli** [comment]
I'm running edge-6bc0302 now. Added just all mods I have in my inactive list, and RimSort didn't even flinch. So either whatever mod developer just fixed some prroblem with it's mod, or the issue was solved.

**Comment by twstagg** [comment]
> I'm running edge-6bc0302 now. Added just all mods I have in my inactive list, and RimSort didn't even flinch. So either whatever mod developer just fixed some problem with it's mod, or the issue was solved.

Glad this is working for you Please let us know if you have any additional issues.
