### ISSUE TITLE
FIXME: "Convert Steam mod to local" does not convert some Steam mods

### ISSUE THREAD

**Issue by glencoe2004** [RimSort/RimSort#155]
**Describe the bug**
As the title says, "Convert Steam mod to local" does not convert some Steam mods, such as Simple Utilities: Fridge.

**To Reproduce**
1. Download Simple Utilities: Fridge
2. Right click on Simple Utilities: Fridge, select "Convert Steam mod to local"
3. Observe as nothing happens.

**Expected behavior**
Simple Utilities: Fridge should be converted to a local mod

**Please complete the following information:**
 - OS: Windows 10
 - RimSort version: RimSort Alpha-v1.0.6.2-hf2
 - Please provide a `RimSort.log`: Log file attached
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled release

**Additional context**
Additionally, RimSort outputs this error:
```
[2023-08-25 14:16:33] ERROR: Failed to convert mod: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2645100914
[2023-08-25 14:16:33] ERROR: Traceback (most recent call last):
  File "E:\Documents\RimPY\model\mod_list.py", line 661, in eventFilter
  File "E:\Documents\RimPY\shutil.py", line 568, in copytree
  File "E:\Documents\RimPY\shutil.py", line 467, in _copytree
  File "E:\Documents\RimPY\os.py", line 225, in makedirs
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\RimWorld\\Mods\\Simple Utilities: Fridge'

```

**Comment by twstagg** [comment]
Fixed as of 8f0c128

will be included in next alpha release. in the meantime, try an edge build that will include this commit soon
