### ISSUE TITLE
FIXME: Low Priority: Uncaught Error on cancel of show_dialogue_file

### ISSUE THREAD

**Issue by Ant-V** [RimSort/RimSort#174]
**Describe the bug:**
As there is no checking in all the show_dialogue_file of the returned value, if the user cancels or closes a show_dialogue_file window, it returns a tuple which cannot be cast into anything useable by normpath, so there is an Uncaught Error.

Example error log:
```
ERROR: Uncaught exception:
Traceback (most recent call last):
  File "~/Sites/RimSort/view/game_configuration_panel.py", line 1186, in set_game_exe_folder
    game_exe_folder_path = os.path.normpath(
                           ^^^^^^^^^^^^^^^^^
     |-> os.path.normpath = <function normpath at 0x1005b1440>
     |-> show_dialogue_file = <function show_dialogue_file at 0x129766a20>
     |-> start_dir = '/Applications/RimWorld.app/'
     => self = <view.game_configuration_panel.GameConfiguration(0x13cc3cd90) at 0x13c71b3c0>
     => possible_dir = '/Applications/RimWorld.app/'

  File "<frozen posixpath>", line 391, in normpath
     => path = ('', '')
TypeError: expected str, bytes or os.PathLike object, not tuple
```

**To Reproduce:**
2. Click on cancel
3. Check log

**Please complete the following information:**
 - OS: _macOS 14.0_
 - RimSort version: _alpha v1.0.6.2-hf_
 - Are you running from Python interpreter or from a compiled RimSort release? _Both_

**Additional comments:**
Since it is only logged as an error with nothing adverse happening and  due to the fact it needs a lot of refactoring to make it go away and clean up,
I don't think it is worth doing anything, but I believe it could be useful to be logged as a known low priority issue in the future

**Comment by Ant-V** [comment]
One thing I did not clarify is this is an issue for selecting files, so `mode="open"`, and is not cause by `mode="open_dir"`, the above sample is from my pull which changes the selection of the game dir to the game app on macOS, so the line is off.

I am including here a full log when I click cancel on `import mod list`

[RimSort.log](https://github.com/RimSort/RimSort/files/12786962/RimSort.log)
