### ISSUE TITLE
FIXME: ModuleNotFoundError: No module named 'steamfiles'

### ISSUE THREAD

**Issue by jefferyharrell** [RimSort/RimSort#230]
**Describe the bug**
Freshly cloning the repository and trying to run the app through the Python interpreter results in a `ModuleNotFoundError` exception.

```
/Users/jefferyharrell/Documents/RimWorld_Modding/GitHub/RimSort/venv/bin/python -m app 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jefferyharrell/Documents/RimWorld_Modding/GitHub/RimSort/app/__main__.py", line 20, in <module>
    from app.controllers.app_controller import AppController
  File "/Users/jefferyharrell/Documents/RimWorld_Modding/GitHub/RimSort/app/controllers/app_controller.py", line 10, in <module>
    from app.views.main_window import MainWindow
  File "/Users/jefferyharrell/Documents/RimWorld_Modding/GitHub/RimSort/app/views/main_window.py", line 17, in <module>
    from app.views.main_content_panel import MainContent
  File "/Users/jefferyharrell/Documents/RimWorld_Modding/GitHub/RimSort/app/views/main_content_panel.py", line 62, in <module>
    from app.sort.dependencies import *
  File "/Users/jefferyharrell/Documents/RimWorld_Modding/GitHub/RimSort/app/sort/dependencies.py", line 3, in <module>
    from app.utils.metadata import MetadataManager
  File "/Users/jefferyharrell/Documents/RimWorld_Modding/GitHub/RimSort/app/utils/metadata.py", line 35, in <module>
    from app.utils.steam.steamfiles.wrapper import acf_to_dict, dict_to_acf
  File "/Users/jefferyharrell/Documents/RimWorld_Modding/GitHub/RimSort/app/utils/steam/steamfiles/wrapper.py", line 3, in <module>
    from steamfiles import acf
ModuleNotFoundError: No module named 'steamfiles'

Process finished with exit code 1
```

**To Reproduce**
1. Clone the repository in the usual fashion
2. Create a virtual environment by running `python3.11 -m venv venv`
3. Activate it with `source venv/bin/activate`
4. Install requirements with `pip install -r requirements.txt`
5. Try to run the application with `python -m app`
6. Observe the aforementioned exception

**Please complete the following information:**
 - OS: macOS 14
 - RimSort version: a23f182f9267a23dea639cff403c92b16fb9d65a

**Additional context**
PyCharm also flags app/utils/steam/steamfiles/wrapper.py:3 as being an unresolved reference.

<img width="505" alt="image" src="https://github.com/RimSort/RimSort/assets/8659114/e8340a75-fcce-44f9-8173-da6f9938f418">

The problem can be worked around by symbolically linking the `steamfiles` package into the repository root with `ln -s submodules/steamfiles/steamfiles steamfiles`, but it seems like this should not be necessary.

**Comment by twstagg** [comment]
`steamfiles` module is not managed from PyPy. This is actually a submodule of ours, as the current PyPy release doesn't compile reliably. 

The submodule points at a repo of mine, so that I can make updates if needed, as the module itself is somewhat unmaintained: https://github.com/twstagg/steamfiles

My fork is based on this one: https://github.com/WinterPhoenix/steamfiles - this contains fix for the setup.py

You can install from one of the forks manually by running `python setup.py install`

This is also something that is done manually with `distribute.py`

Closing this as it really isn't an issue if you install the module. People cloning the repository fresh should just run `distribute.py` once if they don't want the hassle of fixing everything manually. If you can't run that, you have steps to do to complete setting up your environment anyway.
