### ISSUE TITLE
FIXME: Unhandled exception on startup

### ISSUE THREAD

**Issue by Nogloon** [RimSort/RimSort#247]
**Describe the bug**
Crash on startup after downloading for the first time

**To Reproduce**
1. Download most recent release
2. Start rimsort.exe
3. crash

**Expected behavior**
Not to crash

**Screenshots**
![image](https://github.com/RimSort/RimSort/assets/85416691/e9266d7f-798f-4326-bcaa-e2266f01e717)

**Please complete the following information:**
 - OS: Windows 11
 - RimSort version: Alpha-v1.0.6.2-hf
 - Please provide a `RimSort.log`: No log file generated
 - Are you running from Python interpreter or from a compiled RimSort release? Release

**Comment by 0xSENNA** [comment]
Deleting the existing settings.json file (located in AppData\Local\RimSort) seems to fix the issue

**Comment by rakunt** [comment]
Hi, very similar exception caught on Linux (Arch 2023.12.01)

```
Gtk-Message: 12:01:28.689: Failed to load module "canberra-gtk-module"
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
[2024-01-25 12:01:31] ERROR: The main application instantiation has failed with an uncaught exception:
[2024-01-25 12:01:31] ERROR: Traceback (most recent call last):
  File "/home/storyteller/RimSort-Alpha-v1.0.6.2-hf_Linux_x86_64/RimSort.py", line 253, in main_thread
  File "/home/storyteller/RimSort-Alpha-v1.0.6.2-hf_Linux_x86_64/RimSort.py", line 180, in __initialize_content
  File "/home/storyteller/RimSort-Alpha-v1.0.6.2-hf_Linux_x86_64/view/main_content_panel.py", line 1291, in _do_refresh
  File "/home/storyteller/RimSort-Alpha-v1.0.6.2-hf_Linux_x86_64/view/main_content_panel.py", line 498, in __refresh_cache_calculations
  File "/home/storyteller/RimSort-Alpha-v1.0.6.2-hf_Linux_x86_64/view/main_content_panel.py", line 549, in _refresh_external_metadata
AttributeError: 'MainContent' object has no attribute 'internal_local_metadata'

```

deleting ```~/.local/share/RimSort/settings.json``` does solve the problem. Thanks!

**Comment by D3nnis3n** [comment]
Getting this on Windows, but only once I select the RimPy Database in the Settings.

**Comment by twstagg** [comment]
This is the workaround for this issue.
