### ISSUE TITLE
FIXME: Attribute Error

### ISSUE THREAD

**Issue by Rimaworld** [RimSort/RimSort#257]
**Describe the bug**
I have encountered the following error when I opened Rimsort. I am using a Mac M2 Pro and have downloaded the latest version. [RimSort-Alpha-v1.0.6.2-hf_Darwin_arm.zip](https://github.com/RimSort/RimSort/releases/download/alpha-v1.0.6.2-hf/RimSort-Alpha-v1.0.6.2-hf_Darwin_arm.zip)

Traceback (most recent call last):
  File "/private/var/folders/nb/hb_szy3n2glc6hv4zbhhgwth0000gn/T/AppTranslocation/FD1BB2A2-1EFF-47A9-B78F-DE59398B8648/d/RimSort.app/Contents/MacOS/RimSort.py", line 253, in main_thread
  File "/private/var/folders/nb/hb_szy3n2glc6hv4zbhhgwth0000gn/T/AppTranslocation/FD1BB2A2-1EFF-47A9-B78F-DE59398B8648/d/RimSort.app/Contents/MacOS/RimSort.py", line 180, in __initialize_content
  File "/private/var/folders/nb/hb_szy3n2glc6hv4zbhhgwth0000gn/T/AppTranslocation/FD1BB2A2-1EFF-47A9-B78F-DE59398B8648/d/RimSort.app/Contents/MacOS/view/main_content_panel.py", line 1291, in _do_refresh
  File "/private/var/folders/nb/hb_szy3n2glc6hv4zbhhgwth0000gn/T/AppTranslocation/FD1BB2A2-1EFF-47A9-B78F-DE59398B8648/d/RimSort.app/Contents/MacOS/view/main_content_panel.py", line 498, in __refresh_cache_calculations
  File "/private/var/folders/nb/hb_szy3n2glc6hv4zbhhgwth0000gn/T/AppTranslocation/FD1BB2A2-1EFF-47A9-B78F-DE59398B8648/d/RimSort.app/Contents/MacOS/view/main_content_panel.py", line 549, in _refresh_external_metadata
AttributeError: 'MainContent' object has no attribute 'internal_local_metadata'

It shuts down immediately after this message appears. 

**To Reproduce**
I've repeated the process of uninstalling and reinstalling several times, but the same issue persists. Despite not making any changes, and consistently downloading that link, it still doesn't work.

**Expected behavior**
I hope it opens properly and doesn't shut down. 

**Screenshots**

**Please complete the following information:**
 - OS: IOS
 - RimSort version: [RimSort-Alpha-v1.0.6.2-hf_Darwin_arm.zip]
 - Please provide a `RimSort.log`:
 - Are you running from Python interpreter or from a compiled RimSort release?

**Comment by tiagofema** [comment]
Same Error. MAC M1 MAX.
