### ISSUE TITLE
FIXME: Error on startup

### ISSUE THREAD

**Issue by LimeFullhammer** [RimSort/RimSort#273]
Currently rimsort opens with message about up-to-date version and then throw error with following:

Traceback (most recent call last):
  File "/opt/rimsort/RimSort.py", line 253, in main_thread
  File "/opt/rimsort/RimSort.py", line 180, in __initialize_content
  File "/opt/rimsort/view/main_content_panel.py", line 1291, in _do_refresh
  File "/opt/rimsort/view/main_content_panel.py", line 498, in __refresh_cache_calculations
  File "/opt/rimsort/view/main_content_panel.py", line 549, in _refresh_external_metadata
AttributeError: 'MainContent' object has no attribute 'internal_local_metadata'

My specs:

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.1.77-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × AMD Ryzen 3 3200G with Radeon Vega Graphics
Memory: 31.0 GB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7A38
System Version: 8.0
Rimsort version: alpha-v1.0.6.2-hf

**Comment by ALE199** [comment]
[2024-03-12 07:44:55] WARNING: Non-Linux platform detected: using multiprocessing.freeze_support() & setting 'spawn' as MP method
[2024-03-12 07:45:13] ERROR: The main application instantiation has failed with an uncaught exception:
[2024-03-12 07:45:13] ERROR: Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\RimWorld\RimSort\RimSort.py", line 253, in main_thread
  File "D:\SteamLibrary\steamapps\common\RimWorld\RimSort\RimSort.py", line 180, in __initialize_content
  File "D:\SteamLibrary\steamapps\common\RimWorld\RimSort\view\main_content_panel.py", line 1291, in _do_refresh
  File "D:\SteamLibrary\steamapps\common\RimWorld\RimSort\view\main_content_panel.py", line 498, in __refresh_cache_calculations
  File "D:\SteamLibrary\steamapps\common\RimWorld\RimSort\view\main_content_panel.py", line 549, in _refresh_external_metadata
AttributeError: 'MainContent' object has no attribute 'internal_local_metadata'

**Comment by LionelColaso** [comment]
Please check if Edge version solves the issue

**Comment by Mamotromico** [comment]
Confirming that the issue seems to be gone. I've used Rimsort a lot during this day and the issue haven't come up once. Kudos!

Also, the new UI/settings look good o/

**Comment by LionelColaso** [comment]
Thanks for conforming, closing the issue as fixed
