### ISSUE TITLE
FIXME: 

### ISSUE THREAD

**Issue by nyabinary** [RimSort/RimSort#294]
**Describe the bug**
Hard crashing every time I click Setup SteamCMD and when trying to download a workshop mod via the Steam App

**To Reproduce**
Steps to reproduce the behavior of the SteamCMD bug:
1. Click on 'Setup SteamCMD.'
2. See error
Steps to reproduce the behavior of the Steam Workshop/App bug:
1. Go to 'Browse Workshop'
2. Click on any mod
3. Click on 'Add to List'
4. Click on 'Download mod(s) (Steam app)'
5. See error

**Expected behavior**
Downloading mods as expected and not crashing

**Screenshots**
```Traceback (most recent call last):
  File "/nix/store/v30fyz12420nz4ll1jj153dvjma6g9lg-rimsort-0-unstable-2024-04-15/lib/python3.11/site-packages/app/views/main_content_panel.py", line 623, in actions_slot
    self._do_setup_steamcmd()
  File "/nix/store/v30fyz12420nz4ll1jj153dvjma6g9lg-rimsort-0-unstable-2024-04-15/lib/python3.11/site-packages/app/views/main_content_panel.py", line 1912, in _do_setup_steamcmd
    self.steamcmd_wrapper.setup_steamcmd(
  File "/nix/store/v30fyz12420nz4ll1jj153dvjma6g9lg-rimsort-0-unstable-2024-04-15/lib/python3.11/site-packages/app/utils/steam/steamcmd/wrapper.py", line 212, in setup_steamcmd
    os.symlink(
FileNotFoundError: [Errno 2] No such file or directory: '' -> '/home/binary/.local/share/RimSort/steam/steamapps/workshop/content/294100'
``` - For the Setup SteamCMD crash
```
Traceback (most recent call last):
  File "/nix/store/v30fyz12420nz4ll1jj153dvjma6g9lg-rimsort-0-unstable-2024-04-15/lib/python3.11/site-packages/app/views/main_content_panel.py", line 2099, in _do_steamworks_api_call_animated
    publishedfileids = check_if_pfids_blacklisted(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/v30fyz12420nz4ll1jj153dvjma6g9lg-rimsort-0-unstable-2024-04-15/lib/python3.11/site-packages/app/utils/metadata.py", line 2183, in check_if_pfids_blacklisted
    if steamdb.get(publishedfileid, {}).get("blacklist"):
       ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
``` For downloading steam workshop mods

**Please complete the following information:**
 - OS: NixOS (Linux)
 - RimSort version:
 - Please provide a `RimSort.log`:
 - Are you running from Python interpreter or from a compiled RimSort release? N/A (Did it via Nix) ``nix run github:vinnymeller/nixpkgs/init-rimsort#rimsort``


**Additional context**
Logs
[RimSort.old.log](https://github.com/RimSort/RimSort/files/15026800/RimSort.old.log)
[RimSort.log](https://github.com/RimSort/RimSort/files/15026799/RimSort.log)

**Comment by vinnymeller** [comment]
@twstagg I haven't had a chance to look into this yet either but just adding that its possible my [ugly patch](https://github.com/NixOS/nixpkgs/blob/15451c7ab2cc881e674ebd25ddc92623a3868458/pkgs/by-name/ri/rimsort/use-writeable-data-folder.patch) I added to get it to run on nix could be a contributor

**Comment by vinnymeller** [comment]
unsure if you're familiar with nix yourself but if you do want to test the nix build you can install nix  ([official installer](https://nixos.org/download/), [alternative-but-preferred installer](https://github.com/DeterminateSystems/nix-installer) (imo)) and run the same command nya gave, `nix run github:vinnymeller/nixpkgs/init-rimsort#rimsort`

**Comment by nyabinary** [comment]
> > @twstagg I haven't had a chance to look into this yet either but just adding that its possible my [ugly patch](https://github.com/NixOS/nixpkgs/blob/15451c7ab2cc881e674ebd25ddc92623a3868458/pkgs/by-name/ri/rimsort/use-writeable-data-folder.patch) I added to get it to run on nix could be a contributor
> 
> It very well could be. With my cursory glance at this patch the other day, I had mostly chalked this patch up to be out of preference, and not necessity. Could you elaborate more on what you are trying to achieve with that patch?
> 
> Here are some other comments I had made to @nyabinary in the RimSort Discord (you can find a Link to that Discord at the bottom of our README.md btw):
> 
> > https://github.com/NixOS/nixpkgs/pull/304943/files#diff-3cc81f9d013a728b899aa7b3cb84d2bfbbd5e2594553c2aa28edcc79dfd319e7
> > I don't really understand the purpose of this patch.
> > We already bundle steam_appid.txt with the application. Not sure why the creation of that file was hardcoded in that patch.
> > Why switch the condition if **name** == "**main**":  for if True:? Tread carefully with this, as the things within that were done purposefully. Particularly the 2nd instance you patch there - will probably break Multiprocessing on non-Linux platforms (non issue I guess if you're just packaging for Nix)
> 
> The other patches seemed fine. I am interested in the fix you did for LD_LIBRARY_PATH in SteamworksPy as well, as if that is something that would be beneficial, we could accept it in an upstream PR possibly.
> 
> ...
> 
> > unsure if you're familiar with nix yourself but if you do want to test the nix build you can install nix ([official installer](https://nixos.org/download/), [alternative-but-preferred installer](https://github.com/DeterminateSystems/nix-installer) (imo)) and run the same command nya gave, `nix run github:vinnymeller/nixpkgs/init-rimsort#rimsort`
> 
> I would be down to try it sometime, but I am a Ubuntu user primarily. RimSort for the most part receives testing on Ubuntu, Debian, and Arch currently.

You can install nix on those distros too with the nix installer :3

**Comment by twstagg** [comment]
After reviewing both logs, this is definitely 2 separate issues. I will be fixing the crash in the provided `RimSort.log` partially.

However, I think the crash you got in the provided `RimSort.old.log` is due to your patch. Or a leftover `settings.json` from a previous version of RimSort maybe?

```
FileNotFoundError: [Errno 2] No such file or directory: '' -> '/home/binary/.local/share/RimSort/steam/steamapps/workshop/content/294100'
]
```

Do you have your local mods dir set to something...?

**Comment by twstagg** [comment]
Please reopen another Issue with the additional info requested regarding your "Setup SteamCMD" crash. The issue with `check_if_pfids_blacklisted` is resolved.

**Comment by nyabinary** [comment]
> After reviewing both logs, this is definitely 2 separate issues. I will be fixing the crash in the provided `RimSort.log` partially.
> 
> However, I think the crash you got in the provided `RimSort.old.log` is due to your patch. Or a leftover `settings.json` from a previous version of RimSort maybe?
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '' -> '/home/binary/.local/share/RimSort/steam/steamapps/workshop/content/294100'
> ]
> ```
> 
> Do you have your local mods dir set to something...?

Yeah, the steamcmd crash was because of not setting my local mod dir to my rimworld folder :3
![image](https://github.com/RimSort/RimSort/assets/97130632/edca8419-386f-40f1-9017-c427e067a6fd)
This happens now, though.
