### ISSUE TITLE
FIXME: Adding a mod fails when the visibility of the mod is unlisted

### ISSUE THREAD

**Issue by nonnonstop** [RimSort/RimSort#328]
**Describe the bug**
When I try to download a mod whose visibility is unlisted (e.g. [NL] Compatible Body 2), the following error occurs.
```
Traceback (most recent call last):
  File "D:\Users\president\Downloads\RimSort-Edge_978b59e_Windows_x86_64\RimSort\app\utils\steam\browser.py", line 184, in _add_collection_or_mod_to_list
  File "D:\Users\president\Downloads\RimSort-Edge_978b59e_Windows_x86_64\RimSort\app\utils\steam\browser.py", line 244, in _add_mod_to_list
IndexError: list index out of range
```

**To Reproduce**
1. Click "Browse Workshop".
2. Open `https://steamcommunity.com/sharedfiles/filedetails/?id=1906148376`.
3. Click "Add to list".
4. An error dialog appears and the application crashes.

**Expected behavior**
The mod is added successfully.
I think SteamCMD can download unlisted mods without logging in.

**Screenshots**
![image](https://github.com/RimSort/RimSort/assets/42905588/076053a2-4fae-4898-89cc-a991e1901593)

**Please complete the following information:**
 - OS: Windows 10
 - RimSort version: Edge 978b59e
 - Please provide a `RimSort.log`: [RimSort.log](https://github.com/RimSort/RimSort/files/15281182/RimSort.log)
 - Are you running from Python interpreter or from a compiled RimSort release?: a compiled release

**Comment by twstagg** [comment]
This is resolved by #655
