### ISSUE TITLE
FIXME: App crashes after open

### ISSUE THREAD

**Issue by Huliiiiii** [RimSort/RimSort#337]
**Describe the bug**
App crashes after open

**To Reproduce**
1. Open rimsort. 
2. An error dialog appears and the application crashes.

**Please complete the following information:**
 - OS: Windows 11 23H2
 - RimSort version: [Edge d43634c](https://github.com/RimSort/RimSort/releases/tag/Edge)
 - Please provide a `RimSort.log`:
```
  Traceback (most recent call last):
  File "E:\Downloads\RimSort\__main__.py", line 81, in main_thread
  File "E:\Downloads\RimSort\app\controllers\app_controller.py", line 63, in run
  File "E:\Downloads\RimSort\app\views\main_window.py", line 159, in initialize_content
  File "E:\Downloads\RimSort\app\views\main_content_panel.py", line 1016, in _do_refresh
  File "E:\Downloads\RimSort\app\views\main_content_panel.py", line 579, in __repopulate_lists
  File "E:\Downloads\RimSort\app\views\main_content_panel.py", line 481, in __insert_data_into_lists
  File "E:\Downloads\RimSort\app\views\mods_panel.py", line 1816, in recreate_mod_list_and_sort
  File "E:\Downloads\RimSort\app\views\mods_panel.py", line 75, in uuid_to_mod_name
AttributeError: 'NoneType' object has no attribute 'lower'
```
 - Are you running from Python interpreter or from a compiled RimSort release?
Compiled

**Comment by hk21702** [comment]
Sorry for the late response. Can you confirm that this issue persists on the latest release?

**Comment by Huliiiiii** [comment]
> Sorry for the late response. Can you confirm that this issue persists on the latest release?

Yes, this is still happening on the latest edge release.

I found the problem, it was caused by a mod template with an empty name in my local file.

**Comment by LionelColaso** [comment]
fix  https://github.com/RimSort/RimSort/commit/86a24cc502d2158219f47edae5ddcfeb52040f70 was not included in will be will  be in next edge

**Comment by hk21702** [comment]
https://github.com/RimSort/RimSort/commit/86a24cc502d2158219f47edae5ddcfeb52040f70 shouldn't affect this crash. It seems to be a metadata bug. @LionelColaso It'll prob be fixed once I finish dealing with my metadata rework

**Comment by Huliiiiii** [comment]
> [86a24cc](https://github.com/RimSort/RimSort/commit/86a24cc502d2158219f47edae5ddcfeb52040f70) shouldn't affect this crash. It seems to be a metadata bug. @LionelColaso It'll prob be fixed once I finish dealing with my metadata rework

I created a pr to fix it. #431
