### ISSUE TITLE
Old versions of Rimsort no longer work, including 1.5.5 for Windows

### ISSUE THREAD

**Issue by RedPine91** [RimSort/RimSort#416]
I didn't like some of the features in 1.0.6 and tried to go back to an earlier version, 1.0.5.5, but the older version no longer works.

**To Reproduce:**
1. Delete current folder of Rimsort.
2. Unzip desired Rimsort folder.
3. Try to run Rimsort.
4. Get a command line error message.

**Screenshots:**

**Please complete the following information:**

- OS: Windows 10
- RimSort version: 1.0.5.5 (issue occurs on 1.0.6 as well.)
- Command line errors:

git not detected in your PATH! Do you have git installed...? git integration will be disabled!
[2024-06-17 23:54:30] WARNING: Running using Nuitka bundle
[2024-06-17 23:54:30] WARNING: Non-Linux platform detected: using multiprocessing.freeze_support() & setting 'spawn' as MP method
[2024-06-17 23:54:30] WARNING: Configured steamcmd prefix does not exist. Creating new steamcmd prefix at:
[2024-06-17 23:54:30] ERROR: The main application instantiation has failed with an uncaught exception:
[2024-06-17 23:54:30] ERROR: Traceback (most recent call last):
  File "C:\Users\jtnpa\OneDrive\Desktop\RimSort\RimSort.py", line 161, in main_thread
  File "C:\Users\jtnpa\OneDrive\Desktop\RimSort\RimSort.py", line 124, in __init__
  File "C:\Users\jtnpa\OneDrive\Desktop\RimSort\view\game_configuration_panel.py", line 340, in __init__
  File "C:\Users\jtnpa\OneDrive\Desktop\RimSort\view\game_configuration_panel.py", line 617, in initialize_storage
  File "C:\Users\jtnpa\OneDrive\Desktop\RimSort\os.py", line 225, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

- Are you running from Python interpreter or from a compiled RimSort release?  I'm using RimSort-Alpha-v1.0.5.5_Windows.zip 

**Additional context:**
RimSort-v1.0.8-Windows_x86_64.zip  works normally.

**Did you first check the wiki for a solution? (macOS Gatekeeper workaround is there)**
No.

**Comment by hk21702** [comment]
We don't intend on supporting older versions, but if I had to guess the issue is due to files generated by the newer versions being incompatible with the older versions. Clear out the generated files in your %appdata%.
