### ISSUE TITLE
FIXME: Crash on trying to build Steam database.

### ISSUE THREAD

**Issue by Raizanad** [RimSort/RimSort#448]
Already reported on #399, just giving each of the 5 crashes a proper tracking method.

To Reproduce:
A. Click build database.
B. It will finish the process but no DB will be built because the following error will show just at the end:

```
Traceback (most recent call last):
  File "E:\Games\Ludeon\RimSort\app\utils\metadata.py", line 2072, in run
  File "E:\Games\Ludeon\RimSort\app\utils\steam\webapi\wrapper.py", line 260, in create_steam_db
  File "E:\Games\Ludeon\RimSort\app\utils\steam\webapi\wrapper.py", line 589, in ISteamUGC_GetAppDependencies
TypeError: 'NoneType' object is not iterable
```

**Comment by twstagg** [comment]
Does this still happen on current release? Can you please provide the info requested in our bug report template?

**Comment by cebarks** [comment]
Closing as fixed. The crash — `TypeError: 'NoneType' object is not iterable` in `ISteamUGC_GetAppDependencies` — was fixed in commit c5f873e4 (2024-07-17) by adding a `None` check before calling `.update()` on pool results:

```python
for result in results:
    if result is not None:
        pfids_appid_deps.update(result)
```

This fix has been on `main` for nearly two years.
