### ISSUE TITLE
FIXME: Crash on migrating mods from local to workshop.

### ISSUE THREAD

**Issue by Raizanad** [RimSort/RimSort#449]
Already reported on #399, just giving each of the 5 crashes a proper tracking method.

A. Try to migrate any mod from local to workshop.
B. Error will show:

```
Traceback (most recent call last):
  File "E:\Games\Ludeon\RimSort\app\views\mods_panel.py", line 1038, in eventFilter
  File "E:\Games\Ludeon\RimSort\pathlib.py", line 871, in __new__
  File "E:\Games\Ludeon\RimSort\pathlib.py", line 509, in _from_parts
  File "E:\Games\Ludeon\RimSort\pathlib.py", line 493, in _parse_args
TypeError: expected str, bytes or os.PathLike object, not dict
```

Band-aid Solutions:
The way the app works right now is that it judges a workshop mod as "proper" if the folder name is a proper number ID. Migrating from workshop to local work wonderfully to be honest, but if this issue proves hard to fix then for the user reading this:
All you have to do is find the numeric code in About.xml and change the folder name to that.

**Comment by cebarks** [comment]
Closing as fixed. The original crash — `TypeError: expected str, bytes or os.PathLike object, not dict` — was caused by untyped settings allowing a `dict` to be passed where a path string was expected. The settings model has since been migrated to `msgspec.Struct` with strict typing, which prevents this class of bug at deserialization time.
