### ISSUE TITLE
Suggestion: Remove the "Add to list" button from the wrong browser windows that would lead to a crash.

### ISSUE THREAD

**Issue by Raizanad** [RimSort/RimSort#452]
This is a very very very low priority crash since it is hard for a user to even get it, and it can be easily circumvented.

On the built-in browser, certain +18 mods (labelled like that due to sensitivity of whatever kind) that require an account or you to click a button to continue saying you are fine with the content, will have an "add to list" button on the top that upon clicking it will produce a crash.

To reproduce:
Copy and paste this link (or any other like it) into the built-in browser while logged out:
https://steamcommunity.com/sharedfiles/filedetails/?id=1548995767 (This is just an example because I found hard finding a "sensitive mod" again to reproduce the issue).
You will get to a warning screen about logging, or press green button to continue.
Add to list.
Crash:
```
Traceback (most recent call last):
  File "E:\Games\Ludeon\RimSort\app\utils\steam\browser.py", line 190, in _add_collection_or_mod_to_list
  File "E:\Games\Ludeon\RimSort\app\utils\steam\browser.py", line 253, in _add_mod_to_list
IndexError: list index out of range
```

**Comment by cebarks** [comment]
Closing as fixed. The original crash — `IndexError: list index out of range` in `_add_mod_to_list` when clicking "Add to list" on age-gated/login-required Steam pages — has been resolved. The browser code now:

1. Uses `extract_page_title_steam_browser()` as a safe fallback instead of raw HTML indexing
2. Validates URL format and shows a warning dialog if parsing fails
3. Only adds the nav bar "Add to list" action when the page is confirmed to be an item/collection page

If this resurfaces, please open a new issue.
