### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'steamfiles'

### ISSUE THREAD

**Issue by Bravleubiytsabotov2013** [RimSort/RimSort#457]
**Describe the bug:**
Traceback (most recent call last):
  File "/home/den/RimSort/build/__main__.dist/__main__.py", line 48, in <module>
  File "/home/den/RimSort/build/__main__.dist/app/controllers/app_controller.py", line 7, in <module app.controllers.app_controller>
  File "/home/den/RimSort/build/__main__.dist/app/controllers/main_window_controller.py", line 6, in <module app.controllers.main_window_controller>
  File "/home/den/RimSort/build/__main__.dist/app/utils/metadata.py", line 36, in <module app.utils.metadata>
  File "/home/den/RimSort/build/__main__.dist/app/utils/steam/steamfiles/wrapper.py", line 3, in <module app.utils.steam.steamfiles.wrapper>
ModuleNotFoundError: No module named 'steamfiles'

**To Reproduce:**
git clone --recurse-submodules -j8 https://github.com/RimSort/RimSort
./distribute.py
cd /home/den/RimSort/build/__main__.dist
./RimSort

**Expected behavior:**
launch rimsort

**Please complete the following information:**

- Operating System: linux nobara 40
- Processor Architecture: x86-64

**Checklist before opening issue:**

- Did you check the wiki for a solution?  -At least I tried.
- Did you make sure this issue wasn't already reported?  -Half.

**Comment by Bravleubiytsabotov2013** [comment]
No longer needed, sorry

**Comment by Bravleubiytsabotov2013** [comment]
No longer needed, sorry
