### ISSUE TITLE
FIXME: git integration on fedora is broken for both db repos and downloading mods

### ISSUE THREAD

**Issue by marouamghar** [RimSort/RimSort#465]
**Describe the bug:**
Trying to manage db repos or downloading git mods fail, with error `GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v --rebase -- origin`. It's able to setup the parent folder locally, and the repo origin url, but the local repo is empty.
  I have git locally, running a `git pull` on those repos work well.

the error message is :
`The configured repo failed to update! Are you connected to the Internet? Is your configured repo valid?
Configured repository: https://github.com/bbradson/Performance-Fish
Traceback (most recent call last):
  File "/home/user1/Downloads/RimSort/app/views/main_content_panel.py", line 2392, in _do_force_update_existing_repo
  File "/home/user1/Downloads/RimSort/git/remote.py", line 1123, in pull
  File "/home/user1/Downloads/RimSort/git/remote.py", line 895, in _get_fetch_info_from_stderr
  File "/home/user1/Downloads/RimSort/git/cmd.py", line 834, in wait
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v --rebase -- origin
  stderr: 'fatal: Updating an unborn branch with changes added to the index.'

`

**To Reproduce:**
It fails for both db github repos (using the default ones from RimSort) and downloading a mod from github. The easiest way to repro it is to try and download performance fish.
1. Go to Download
2. Click on Add Git mod
3. Put https://github.com/bbradson/Performance-Fish

- Operating System: [e.g. Windows 11]
- Processor Architecture: [Arm/x86/Unknown]
- RimSort version: 1.08
- Please provide a `RimSort.log`:
- Are you running from the Python interpreter or from a compiled RimSort release? release

**Additional context:**
When running RimSort through cmdline, the only weird log was :
[WARNING][2024-07-03 17:14:32][81736][MainThread][main_content_panel][_do_force_update_existing_repo][2387] : Target branch not found.

**Comment by hk21702** [comment]
I'm currently doing a full migration from GitPython to PyGit2 (#578). I'm not sure if this issue will be solved by it, but will need to check afterward.

**Comment by hk21702** [comment]
I just want to check. Does this issue continue to occur when running from the Python interpreters? That is, not using the pre-compiled Ubuntu-specific releases.

**Comment by CharlyMH** [comment]
I don't know how to run this from the Python interpreters, but from the pre-compiled releases the issue continues.

**Comment by LionelColaso** [comment]
Issue fixed with the new pygit2 module 
reopen if still not working
