### ISSUE TITLE
FIXME: 

### ISSUE THREAD

**Issue by PaterFrog** [RimSort/RimSort#550]
**Describe the bug:**
Probably an infinite loop of some kind, got some weird looping audio, etc., until RimSort decided to end things and gave me an error. Very strange. It's the only time I've had this crash happen. Nothing particularly obvious to kick it off either, I just hit the refresh button.

Here's the error I got:

Traceback (most recent call last):
  File "S:\Games1TBSSD\steamapps\common\RimWorld\RimSort\app\utils\metadata.py", line 1181, in process_update
  File "S:\Games1TBSSD\steamapps\common\RimWorld\RimSort\app\utils\metadata.py", line 977, in compile_metadata
  File "S:\Games1TBSSD\steamapps\common\RimWorld\RimSort\app\utils\metadata.py", line 1839, in add_load_rule_to_mod
KeyError: 'd831b6b2-cdce-4125-a76c-da6f11492252'

- Win 10
- Processor Architecture: x86
- RimSort version: 1.0.9
- Please provide a `RimSort.log`:  [debug.log](https://github.com/user-attachments/files/16508234/debug.log)
- compiled release

All in all, I'm not worrying about this error. Seems more like an edge case than something that'll regularly pop up.

**Comment by LionelColaso** [comment]
@PaterFrog Is this still a issue ?
