### ISSUE TITLE
Add a flatpak version of the app

### ISSUE THREAD

**Issue by yodatak** [RimSort/RimSort#628]
### Origin of idea

I want to use it on steam deck and bazzite ( and on fedora the curent build segfault)

### Suggestion/proposed solution?

Add a flathub/flatpak package to make installation on linux easy and not distribution dependent

I make a WIP flatpak here if somebody  want to help it could be awsome !
https://github.com/yodatak/flathub/tree/RimSort

i'm stuck on this 

[📦 org.RimSort.RimSort ~]$ RimSort 
Traceback (most recent call last):
  File "/app/bin/RimSort", line 37, in <module>
    from app.controllers.app_controller import AppController
  File "/app/bin/app/controllers/app_controller.py", line 7, in <module>
    from app.controllers.main_window_controller import MainWindowController
  File "/app/bin/app/controllers/main_window_controller.py", line 6, in <module>
    from app.utils.metadata import MetadataManager
  File "/app/bin/app/utils/metadata.py", line 30, in <module>
    from app.utils.steam.steamcmd.wrapper import SteamcmdInterface
  File "/app/bin/app/utils/steam/steamcmd/wrapper.py", line 23, in <module>
    from app.windows.runner_panel import RunnerPanel
  File "/app/bin/app/windows/runner_panel.py", line 20, in <module>
    from app.utils.steam.webapi.wrapper import (
  File "/app/bin/app/utils/steam/webapi/wrapper.py", line 18, in <module>
    from app.utils.steam.steamworks.wrapper import SteamworksAppDependenciesQuery
  File "/app/bin/app/utils/steam/steamworks/wrapper.py", line 17, in <module>
    from steamworks import STEAMWORKS  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'steamworks'

or 
[📦 org.RimSort.RimSort app]$ python3 __main__.py 
Traceback (most recent call last):
  File "/app/bin/app/__main__.py", line 37, in <module>
    from app.controllers.app_controller import AppController
ModuleNotFoundError: No module named 'app

my tree 

drwxr-xr-x. 1 yodatak yodatak      256  1 janv.  1970 .
drwxr-xr-x. 1 yodatak yodatak      302  5 oct.  18:45 ..
drwxr-xr-x. 1 yodatak yodatak      120  1 janv.  1970 app
-rwxr-xr-x. 2 yodatak yodatak      240  1 janv.  1970 imageio_download_bin
-rwxr-xr-x. 2 yodatak yodatak      236  1 janv.  1970 imageio_remove_bin
drwxr-xr-x. 1 yodatak yodatak      358  1 janv.  1970 libs
-rwxr-xr-x. 2 yodatak yodatak 19260320  1 janv.  1970 maturin
-rwxr-xr-x. 2 yodatak yodatak      214  1 janv.  1970 natsort
-rwxr-xr-x. 5 yodatak yodatak      232  1 janv.  1970 normalizer
-rwxr-xr-x. 3 yodatak yodatak    14624  1 janv.  1970 QtWebEngineProcess
-rwxr-xr-x. 2 yodatak yodatak     8225  1 janv.  1970 RimSort
-rwxr-xr-x. 3 yodatak yodatak      239  1 janv.  1970 shiboken6
-rwxr-xr-x. 3 yodatak yodatak      243  1 janv.  1970 shiboken6-genpyi
-rwxr-xr-x. 2 yodatak yodatak      216  1 janv.  1970 watchmedo

### Code of Conduct

I agree to follow this project's Code of Conduct

### Duplicate Issue Check

I've checked for similar issues and didn't find anything

### Wiki/FAQ Check

I've checked the Wiki for a solution and didn't find a solution

**Comment by hk21702** [comment]
Needs the steamworks python library. See distribute.py for the script to build rimsort locally. It also gets required libs and binaries.

**Comment by yodatak** [comment]
For now i stuck with ditribute.py that use web ( flatpak are build alway on offline ) 

i use       - ./distribute.py --build-steamworkspy --skip-submodules --skip-build --skip-pip
but it stuck 
on line 
    print("Getting Steamworks SDK...")
    if os.path.exists(STEAMWORKS_SDK_PATH):
        print("Existing SDK found. Removing, and re-downloading fresh copy.")
        shutil.rmtree(STEAMWORKS_SDK_PATH)
    with ZipFile(BytesIO(handle_request(STEAMWORKS_SDK_URL).content)) as zipobj:
        zipobj.extractall(STEAMWORKS_PY_PATH)

have you posibility to update script to support offline install of steamworks instead of url download ?

  File "/app/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /oceancabbage/RimSort/raw/steamworks-sdk/steamworks_sdk_155.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3f1fa780d0>: Failed to resolve 'github.com' ([Errno -3] Temporary failure in name resolution)"))
Error: module RimSort: Le processus fils s’est terminé avec le code 1

**Comment by yodatak** [comment]
With dirty patch i now compile the app but i'm stuck with ModuleNotFoundError: No module named 'steamworks'

Where do i have to put the libs ?

Form flatpak python i got 
# >>> sys.path
# ['', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/app/lib/python3.11/site-packages', '/usr/lib/python3.11/site-packages']

How can i set python to take the python libs of steamworks too ?

**Comment by yodatak** [comment]
i somebody can help i think it don't lack many thinks to make it works !
https://github.com/yodatak/flathub/tree/RimSort

**Comment by yodatak** [comment]
Hi i done a build an its works i think there is a issue or something i don't understand but its run on my fedora 42 on flatpak ! 

If someone want to test and would be interested to publish on flathub are you interested  @hk21702  ?

Its works here ( it try to compile in CI )
https://github.com/flathub/flathub/pull/6197

I think we could upstream some part of modifications to make flathub publication easier ( i did not test yet on steam deck only desktop for now)

**Comment by yodatak** [comment]
If interested too to test @hideki2k02

**Comment by yodatak** [comment]
https://github.com/flathub/flathub/pull/6197

there is a test build to test if someone want to help

**Comment by yodatak** [comment]
its working but not in flathub now but i use it on my computer if somebody want to test to irons things

https://github.com/flathub/flathub/pull/6197#issuecomment-3066131077

**Comment by yodatak** [comment]
@LionelColaso  or @Ocean456  can you review my work and check if i don't forget anything i thing there is a issue with the todd binary detection because its don't find the binary thanks !

**Comment by normous** [comment]
Hi @yodatak, have you gotten this to work?  I'd be happy to help test on Steam Deck!

**Comment by AbrahamPicos** [comment]
I build and ran it on Gentoo, and it seems to work. The only issues I've noticed so far are:
1. The main window title bar displays "unknown version".
2. Steamcmd doesn't run due to missing 32-bit dependencies.

**Comment by AbrahamPicos** [comment]
I got steamcmd working by adding multiarch support as follows:
```
finish-args:
    - --allow=multiarch

add-extensions:
  org.freedesktop.Platform.Compat.i386:
    directory: lib/i386-linux-gnu
    version: '24.08'

modules:
  - name: RimSort
    build-commands:
      - mkdir -p /app/lib/i386-linux-gnu
```
I downloaded a couple of mods and they appeared in the "Mods" folder as expected.

**Comment by yodatak** [comment]
Hello what is need to make this think realty in upstream ?
