### ISSUE TITLE
FIXME: 1.0.5.2 for windows could not execute, git need to be installed

### ISSUE THREAD

**Issue by kn007** [RimSort/RimSort#92]
```
Traceback (most recent call last):
  File "C:\Users\kn007\Desktop\RimSort\git\__init__.py", line 89, in <module git>
  File "C:\Users\kn007\Desktop\RimSort\git\__init__.py", line 76, in refresh
  File "C:\Users\kn007\Desktop\RimSort\git\cmd.py", line 392, in refresh
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kn007\Desktop\RimSort\RimSort.py", line 23, in <module>
  File "C:\Users\kn007\Desktop\RimSort\view\main_content_panel.py", line 22, in <module view.main_content_panel>
  File "C:\Users\kn007\Desktop\RimSort\git\__init__.py", line 91, in <module git>
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

```

**Comment by twstagg** [comment]
@kn007 Thanks for your report!

Git is now a dependency. This exception shouldn't be entirely critical as long as we handle it. In order to use some of the DB tools, git is now needed. I'll also be adding another option to get DB without the git integration.

@cylian914 
`import git.exc.GitCommandError`

Then, for the import statement + code that actually does the git commands (these ones are already try/catch wrapped...)

You can do `except GitCommandError:`

And then do a `show_dialogue_conditional`

"Git was not detected as installed. Do you want to open page to download and install?" NO/YES

Then if they click yes, just have it open the URL to git-scm download page.

**Comment by twstagg** [comment]
Will be included in next release. Fixed in 7a46c27cb5f989bfe2e99bd2421da373ce1f9f94

Please install `git`: https://git-scm.com/downloads

**Comment by kn007** [comment]
look like something wrong for urllib3 module?

```
Traceback (most recent call last):
  File "C:\DATA\tools\RimSort\urllib3\connectionpool.py", line 700, in urlopen
  File "C:\DATA\tools\RimSort\urllib3\connectionpool.py", line 996, in _prepare_proxy
  File "C:\DATA\tools\RimSort\urllib3\connection.py", line 369, in connect
  File "C:\DATA\tools\RimSort\urllib3\connection.py", line 504, in _connect_tls_proxy
  File "C:\DATA\tools\RimSort\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "C:\DATA\tools\RimSort\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "C:\DATA\tools\RimSort\ssl.py", line 500, in wrap_socket
  File "C:\DATA\tools\RimSort\ssl.py", line 1040, in _create
  File "C:\DATA\tools\RimSort\ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DATA\tools\RimSort\requests\adapters.py", line 489, in send
  File "C:\DATA\tools\RimSort\urllib3\connectionpool.py", line 787, in urlopen
  File "C:\DATA\tools\RimSort\urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/RimSort/RimSort/releases/latest (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DATA\tools\RimSort\view\main_content_panel.py", line 829, in actions_slot
  File "C:\DATA\tools\RimSort\view\main_content_panel.py", line 982, in _do_check_for_update
  File "C:\DATA\tools\RimSort\requests\api.py", line 73, in get
  File "C:\DATA\tools\RimSort\requests\api.py", line 59, in request
  File "C:\DATA\tools\RimSort\requests\sessions.py", line 587, in request
  File "C:\DATA\tools\RimSort\requests\sessions.py", line 701, in send
  File "C:\DATA\tools\RimSort\requests\adapters.py", line 563, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/RimSort/RimSort/releases/latest (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
```

**Comment by cylian914** [comment]
It's a SSL error, does https site work on your browser ?

**Comment by kn007** [comment]
> requests

sure.
i found the problem, if setting system proxy(even the proxy service is fine), it will fail.
working fine without system proxy

**Comment by kn007** [comment]
app crash with right click "Opening url in browser", 1.0.5.1 working fine.


bad log file rogic change, when app crash, log lost if running app again.

The following log was found from in  user_temp\rimsort.log after the crash
```
[INFO][2023-06-09 20:46:13][37504][model.mod_list][eventFilter][123] : USER ACTION: Open right-click mod_list_item contextMenu
[DEBUG][2023-06-09 20:46:13][37504][model.mod_list][eventFilter][178] : Tracking PublishedFileID for ISteamUGC/UnsubscribeItem: 1713367505
[INFO][2023-06-09 20:46:14][37504][model.mod_list][eventFilter][279] : Opening url in browser: https://steamcommunity.com/sharedfiles/filedetails/?id=1713367505
```

**Comment by twstagg** [comment]
@kn007 Thank you for your reports. I will find some time to look into these issues this weekend. 

Could you please attach full logs (with DEBUG mode on) in conjunction with exact steps to reproduce in the respective issues?

Additionally, I'll be releasing a patch 1.0.5.3 this weekend if you could test with that version once I have it out.

**Comment by kn007** [comment]
give me a second, i will post logs to #99 and #100.

anytime for test.

**Comment by kn007** [comment]
@twstagg logs has been uploaded to #99 and #100

**Comment by kn007** [comment]
just a record

```
[2023-06-11 03:08:27] WARNING: Checking for RimSort update...
[2023-06-11 03:08:28] WARNING: Current RimSort release found: alpha-v1.0.5.3
[2023-06-11 03:08:28] WARNING: Current RimSort version found: alpha-v1.0.5.2
[2023-06-11 03:08:30] WARNING: Windows system detected with a 64bit Intel64 Family 6 Model 183 Stepping 1, GenuineIntel CPU...
[2023-06-11 03:08:30] WARNING: Attempting to retrieve archive from release: RimSort-Alpha-v1.0.5.3_Windows.zip
[2023-06-11 03:08:30] WARNING: Downloading & extracting RimSort release from: https://github.com/RimSort/RimSort/releases/download/alpha-v1.0.5.3/RimSort-Alpha-v1.0.5.3_Windows.zip
[2023-06-11 03:08:38] ERROR: The main application loop has failed with an uncaught exception
Traceback (most recent call last):
  File "C:\DATA\tools\RimSort\view\main_content_panel.py", line 829, in actions_slot
  File "C:\DATA\tools\RimSort\view\main_content_panel.py", line 1079, in _do_check_for_update
  File "C:\DATA\tools\RimSort\shutil.py", line 740, in rmtree
  File "C:\DATA\tools\RimSort\shutil.py", line 613, in _rmtree_unsafe
  File "C:\DATA\tools\RimSort\shutil.py", line 618, in _rmtree_unsafe
  File "C:\DATA\tools\RimSort\shutil.py", line 616, in _rmtree_unsafe
PermissionError: [WinError 5] Access Deny: 'C:\\DATA\\tools\\RimSort\\charset_normalizer\\md.pyd'
```

**Comment by kn007** [comment]
> Please test the "Check for updates" which can be found in the top-right of the application as of Alpha 1.0.5.2 release - you should now be able to upgrade in-place! 😄


@twstagg 

```
[2023-06-11 03:08:27] WARNING: Checking for RimSort update...
[2023-06-11 03:08:28] WARNING: Current RimSort release found: alpha-v1.0.5.3
[2023-06-11 03:08:28] WARNING: Current RimSort version found: alpha-v1.0.5.2
[2023-06-11 03:08:30] WARNING: Windows system detected with a 64bit Intel64 Family 6 Model 183 Stepping 1, GenuineIntel CPU...
[2023-06-11 03:08:30] WARNING: Attempting to retrieve archive from release: RimSort-Alpha-v1.0.5.3_Windows.zip
[2023-06-11 03:08:30] WARNING: Downloading & extracting RimSort release from: https://github.com/RimSort/RimSort/releases/download/alpha-v1.0.5.3/RimSort-Alpha-v1.0.5.3_Windows.zip
[2023-06-11 03:08:38] ERROR: The main application loop has failed with an uncaught exception
Traceback (most recent call last):
  File "C:\DATA\tools\RimSort\view\main_content_panel.py", line 829, in actions_slot
  File "C:\DATA\tools\RimSort\view\main_content_panel.py", line 1079, in _do_check_for_update
  File "C:\DATA\tools\RimSort\shutil.py", line 740, in rmtree
  File "C:\DATA\tools\RimSort\shutil.py", line 613, in _rmtree_unsafe
  File "C:\DATA\tools\RimSort\shutil.py", line 618, in _rmtree_unsafe
  File "C:\DATA\tools\RimSort\shutil.py", line 616, in _rmtree_unsafe
PermissionError: [WinError 5] Access Deny: 'C:\\DATA\\tools\\RimSort\\charset_normalizer\\md.pyd'
```
